### ISSUE TITLE
Opening System Configuration in Rosalina causes a crash.

### ISSUE THREAD

**Issue by Lesking72** [WerWolv98/PowerPrevent_SysModule#1]
GitHub only accepts some file types so I zipped the crash dump
[Crash Dump.zip](https://github.com/WerWolv98/PowerPrevent_SysModule/files/1913213/Crash.Dump.zip)

Luma settings:
Stable release 9.0
CPU clock set to default
Game patching enabled, ACNL texture mods
Show NAND or user string in system settings on

**Comment by WerWolv** [comment]
Fixed in the latest version.
